language: go

addons:
  postgresql: "9.3"

services:
  - postgresql

go:
  - 1.2

env:
  - GOENV=test

before_install:
  - go install -a -race std
  - go get github.com/tools/godep
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - export PATH=$HOME/gopath/bin:$PATH
  - godep get
  - make bootstrap

script:
  - godep go test -race -tags=integration ./...
