---
http_interactions:
- request:
    method: post
    uri: https://api.github.com/repos/shipr-test/test-repo/deployments/2554/statuses
    body:
      encoding: UTF-8
      string: "{\"state\":\"pending\"}"
    headers:
      User-Agent:
      - Faraday v0.8.8
      Accept:
      - application/vnd.github.cannonball-preview+json
      Authorization:
      - token <GITHUB_DEPLOY_TOKEN>
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 201
      message: Created
    headers:
      Server:
      - GitHub.com
      Date:
      - Fri, 21 Mar 2014 21:09:44 GMT
      Content-Type:
      - application/json; charset=utf-8
      Status:
      - 201 Created
      X-Ratelimit-Limit:
      - '5000'
      X-Ratelimit-Remaining:
      - '4979'
      X-Ratelimit-Reset:
      - '1395437744'
      Cache-Control:
      - private, max-age=60, s-maxage=60
      Etag:
      - "\"879bf1215591e3935c12322005d65092\""
      X-Oauth-Scopes:
      - admin:repo_hook, repo_deployment
      X-Accepted-Oauth-Scopes:
      - ''
      Location:
      - https://api.github.com/repos/shipr-test/test-repo/deployments/2554/statuses/8554
      Vary:
      - Accept, Authorization, Cookie, X-GitHub-OTP
      X-Github-Media-Type:
      - github.cannonball-preview; format=json
      X-Content-Type-Options:
      - nosniff
      Content-Length:
      - '1176'
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Expose-Headers:
      - ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset,
        X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
      Access-Control-Allow-Origin:
      - "*"
      X-Github-Request-Id:
      - 324FD279:26C3:13F53B3:532CAA98
    body:
      encoding: UTF-8
      string: "{\"url\":\"https://api.github.com/repos/shipr-test/test-repo/deployments/2554/statuses/8554\",\"id\":8554,\"state\":\"pending\",\"payload\":{},\"description\":null,\"target_url\":null,\"creator\":{\"login\":\"shipr-test\",\"id\":7026228,\"avatar_url\":\"https://avatars.githubusercontent.com/u/7026228?\",\"gravatar_id\":\"40ef4cb7b26339e19d42761568ae52df\",\"url\":\"https://api.github.com/users/shipr-test\",\"html_url\":\"https://github.com/shipr-test\",\"followers_url\":\"https://api.github.com/users/shipr-test/followers\",\"following_url\":\"https://api.github.com/users/shipr-test/following{/other_user}\",\"gists_url\":\"https://api.github.com/users/shipr-test/gists{/gist_id}\",\"starred_url\":\"https://api.github.com/users/shipr-test/starred{/owner}{/repo}\",\"subscriptions_url\":\"https://api.github.com/users/shipr-test/subscriptions\",\"organizations_url\":\"https://api.github.com/users/shipr-test/orgs\",\"repos_url\":\"https://api.github.com/users/shipr-test/repos\",\"events_url\":\"https://api.github.com/users/shipr-test/events{/privacy}\",\"received_events_url\":\"https://api.github.com/users/shipr-test/received_events\",\"type\":\"User\",\"site_admin\":false},\"created_at\":\"2014-03-21T21:09:44Z\",\"updated_at\":\"2014-03-21T21:09:44Z\"}"
    http_version: 
  recorded_at: Fri, 21 Mar 2014 21:09:48 GMT
recorded_with: VCR 2.8.0
